/**
 * vLLM Client — OpenAI-compatible client for self-hosted local LLMs.
 *
 * Talks to a vLLM instance serving Llama 3.3 70B, Mistral, or Phi-3 on
 * TechFides GPU infrastructure. Falls back to mock mode in dev when no
 * GPU is available.
 *
 * Deployment: see docs/INFRA-VLLM.md
 */

export interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface ChatCompletionOptions {
  messages: ChatMessage[];
  model?: string;
  temperature?: number;
  maxTokens?: number;
  responseFormat?: "text" | "json_object";
}

export interface ChatCompletionResponse {
  content: string;
  model: string;
  usage: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}

const MOCK_MODE = process.env.VLLM_MOCK_MODE === "true";
const BASE_URL = process.env.VLLM_BASE_URL || "http://localhost:8000/v1";
const API_KEY = process.env.VLLM_API_KEY || "";
const DEFAULT_MODEL = process.env.VLLM_MODEL || "meta-llama/Llama-3.3-70B-Instruct";

/**
 * Generate a chat completion via the local vLLM instance.
 *
 * In mock mode (dev without GPU), returns a deterministic stub response so
 * the rest of the pipeline can be developed and tested.
 */
export async function chatCompletion(
  options: ChatCompletionOptions
): Promise<ChatCompletionResponse> {
  if (MOCK_MODE) {
    return mockChatCompletion(options);
  }

  const response = await fetch(`${BASE_URL}/chat/completions`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${API_KEY}`,
    },
    body: JSON.stringify({
      model: options.model || DEFAULT_MODEL,
      messages: options.messages,
      temperature: options.temperature ?? 0.7,
      max_tokens: options.maxTokens ?? 1024,
      response_format:
        options.responseFormat === "json_object"
          ? { type: "json_object" }
          : undefined,
    }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`vLLM request failed: ${response.status} ${text}`);
  }

  const data = (await response.json()) as {
    choices: { message: { content: string } }[];
    model: string;
    usage: { prompt_tokens: number; completion_tokens: number; total_tokens: number };
  };

  return {
    content: data.choices[0]?.message?.content || "",
    model: data.model,
    usage: {
      promptTokens: data.usage.prompt_tokens,
      completionTokens: data.usage.completion_tokens,
      totalTokens: data.usage.total_tokens,
    },
  };
}

/**
 * Mock response for dev mode. Returns deterministic stub data so the
 * Persona Engine can be developed without a GPU.
 */
function mockChatCompletion(
  options: ChatCompletionOptions
): ChatCompletionResponse {
  const lastUserMessage =
    options.messages.filter((m) => m.role === "user").pop()?.content || "";

  let content: string;

  if (options.responseFormat === "json_object") {
    // Return a mock outreach sequence in JSON
    content = JSON.stringify({
      sequenceId: `mock_${Date.now()}`,
      steps: [
        {
          order: 1,
          delayDays: 0,
          subject: "[MOCK] AI sovereignty for your team",
          body:
            "[MOCK RESPONSE — vLLM not connected] This is a placeholder generated by the dev mock. In production, Llama 3.3 70B would generate a personalized message based on the lead's enrichment data.",
          personalizationAnchor: "mock_anchor",
          cta: "15-min discovery call",
        },
      ],
    });
  } else {
    content = `[MOCK vLLM response — set VLLM_MOCK_MODE=false and configure VLLM_BASE_URL to use the real local LLM. Echoing: ${lastUserMessage.slice(0, 100)}]`;
  }

  return {
    content,
    model: `mock-${DEFAULT_MODEL}`,
    usage: {
      promptTokens: 0,
      completionTokens: 0,
      totalTokens: 0,
    },
  };
}

/**
 * Health check for the vLLM instance.
 */
export async function vllmHealthCheck(): Promise<{
  ok: boolean;
  mock: boolean;
  baseUrl: string;
  error?: string;
}> {
  if (MOCK_MODE) {
    return { ok: true, mock: true, baseUrl: BASE_URL };
  }

  try {
    const response = await fetch(`${BASE_URL}/models`, {
      headers: { Authorization: `Bearer ${API_KEY}` },
    });
    return {
      ok: response.ok,
      mock: false,
      baseUrl: BASE_URL,
      error: response.ok ? undefined : `HTTP ${response.status}`,
    };
  } catch (e) {
    return {
      ok: false,
      mock: false,
      baseUrl: BASE_URL,
      error: e instanceof Error ? e.message : "Unknown error",
    };
  }
}
